### ISSUE TITLE
Error: spawnSync /usr/local/bin/node ETIMEDOUT

### ISSUE THREAD

**Issue by Greenwicher** [Yikun/hexo-generator-douban#3]
Hi Yikun,

Thanks for your wonderful plugins for douban books. It's really impressive. However, I encountered some troublesome issues. Please see the error information below. 

Thanks,
Weizhi

**Comment by Greenwicher** [comment]
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: spawnSync /usr/local/bin/node ETIMEDOUT
    at exports._errnoException (util.js:856:11)
    at Object.spawnSync (child_process.js:443:20)
    at request (/Users/liuweizhi/Dropbox/study/Project/greenwicher.me/blog/node_modules/urllib-sync/index.js:33:16)
    at Hexo.module.exports (/Users/liuweizhi/Dropbox/study/Project/greenwicher.me/blog/node_modules/hexo-generator-douban/lib/generator.js:16:15)
    at Hexo.tryCatcher (/Users/liuweizhi/Dropbox/study/Project/greenwicher.me/blog/node_modules/bluebird/js/main/util.js:26:23)
    at Hexo.<anonymous> (/Users/liuweizhi/Dropbox/study/Project/greenwicher.me/blog/node_modules/bluebird/js/main/method.js:15:34)
    at /Users/liuweizhi/Dropbox/study/Project/greenwicher.me/blog/node_modules/hexo/lib/hexo/index.js:325:24
    at tryCatcher (/Users/liuweizhi/Dropbox/study/Project/greenwicher.me/blog/node_modules/bluebird/js/main/util.js:26:23)
    at MappingPromiseArray._promiseFulfilled (/Users/liuweizhi/Dropbox/study/Project/greenwicher.me/blog/node_modules/bluebird/js/main/map.js:56:38)
    at MappingPromiseArray.init (/Users/liuweizhi/Dropbox/study/Project/greenwicher.me/blog/node_modules/bluebird/js/main/promise_array.js:92:18)
    at MappingPromiseArray.init (/Users/liuweizhi/Dropbox/study/Project/greenwicher.me/blog/node_modules/bluebird/js/main/map.js:29:23)
    at Async._drainQueue (/Users/liuweizhi/Dropbox/study/Project/greenwicher.me/blog/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/liuweizhi/Dropbox/study/Project/greenwicher.me/blog/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate](/Users/liuweizhi/Dropbox/study/Project/greenwicher.me/blog/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback](timers.js:383:17)
FATAL spawnSync /usr/local/bin/node ETIMEDOUT
Error: spawnSync /usr/local/bin/node ETIMEDOUT
    at exports._errnoException (util.js:856:11)
    at Object.spawnSync (child_process.js:443:20)
    at request (/Users/liuweizhi/Dropbox/study/Project/greenwicher.me/blog/node_modules/urllib-sync/index.js:33:16)
    at Hexo.module.exports (/Users/liuweizhi/Dropbox/study/Project/greenwicher.me/blog/node_modules/hexo-generator-douban/lib/generator.js:16:15)
    at Hexo.tryCatcher (/Users/liuweizhi/Dropbox/study/Project/greenwicher.me/blog/node_modules/bluebird/js/main/util.js:26:23)
    at Hexo.<anonymous> (/Users/liuweizhi/Dropbox/study/Project/greenwicher.me/blog/node_modules/bluebird/js/main/method.js:15:34)
    at /Users/liuweizhi/Dropbox/study/Project/greenwicher.me/blog/node_modules/hexo/lib/hexo/index.js:325:24
    at tryCatcher (/Users/liuweizhi/Dropbox/study/Project/greenwicher.me/blog/node_modules/bluebird/js/main/util.js:26:23)
    at MappingPromiseArray._promiseFulfilled (/Users/liuweizhi/Dropbox/study/Project/greenwicher.me/blog/node_modules/bluebird/js/main/map.js:56:38)
    at MappingPromiseArray.init (/Users/liuweizhi/Dropbox/study/Project/greenwicher.me/blog/node_modules/bluebird/js/main/promise_array.js:92:18)
    at MappingPromiseArray.init (/Users/liuweizhi/Dropbox/study/Project/greenwicher.me/blog/node_modules/bluebird/js/main/map.js:29:23)
    at Async._drainQueue (/Users/liuweizhi/Dropbox/study/Project/greenwicher.me/blog/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/liuweizhi/Dropbox/study/Project/greenwicher.me/blog/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate](/Users/liuweizhi/Dropbox/study/Project/greenwicher.me/blog/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback](timers.js:383:17)

**Comment by Yikun** [comment]
@Greenwicher 您好，感谢对插件的关注与肯定。

这个插件的原理是通过Douban官方的API去获取你的豆瓣信息。因此，需要配置你自己的Douban user id。

但是我看你的[_config.yml](https://github.com/Greenwicher/blog/blob/source/_config.yml)里似乎并没有对douban的user进行配置，请参考[Readme](https://github.com/Yikun/hexo-generator-douban/blob/master/README.md)或者我的[_config.yml](https://github.com/Yikun/yikun.github.com/blob/hexo/_config.yml)进行配置。

如果已经进行配置了，可以尝试着用浏览器访问http://api.douban.com/v2/book/user/63751575/collections?status=read，其中63751575替换为为你的Douban user id，如果可以正常访问，并且能够get到你都阅读信息，那么这个插件应该也是可以工作。

BTW，这个豆瓣插件是和我现在用的主题样式强相关的，css文件静态的写在代码里，可能不太符合你的样式要求，如果需要修改样式，可能需要你自己对代码进行修改。

Regards,
Yikun

**Comment by Greenwicher** [comment]
Hi Yikun,

谢谢您的及时回复。我有在_config.yml里有设置douban user id和plugins。我的id是用Greenwicher而不是数字代码，通过api发现也可以获取信息。

上面的错误会经常出现，多试几次之后才能成功。不知道是不是spawnSync有些冲突？

Best,
Weizhi

**Comment by Yikun** [comment]
我试了下你的ID，在我的环境中没有问题，我的环境是：

```
➜  yikun.github.com git:(hexo) ✗ hexo -v
hexo: 3.0.1
os: Darwin 15.3.0 darwin x64
http_parser: 2.3
node: 0.12.2
v8: 3.28.73
uv: 1.4.2-node1
zlib: 1.2.8
modules: 14
openssl: 1.0.1m
```

因为我也对hexo了解得不是特别深，只是满足自用而已，希望提供的信息能够帮助到你，如果有更好的解决方案，也请告知，谢谢。：）

Regards,
Yikun

**Comment by Greenwicher** [comment]
谢谢啦，虽然报错中有hexo-generator-douban的信息，但似乎可能是我自己装的其他插件有冲突（hexo-renderer-org）。hexo-renderer-org会在我的_posts文件夹下建立和文章同名的文件夹，我把其中一个给删掉了（虽然是空的）。后来我又新建了这个文件夹之后，就再也没出先这个问题啦~ 多谢帮忙

**Comment by Yikun** [comment]
不客气~

**Comment by percy507** [comment]
@Yikun 

> $ hexo g -d
> INFO  Start processing
> FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
> Error: spawnSync E:\Installed_Software\nodejs\node.exe ETIMEDOUT
>     at exports._errnoException (util.js:1008:11)
>     at Object.spawnSync (child_process.js:453:20)
>     at request (E:\GitHub\hexo\blog\node_modules\urllib-sync\index.js:33:16)
>     at Hexo.module.exports (E:\GitHub\hexo\blog\node_modules\hexo-generator-douban\lib\generator.js:16:15)
>     at Hexo.tryCatcher (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
>     at Hexo.<anonymous> (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\method.js:15:34)
>     at E:\GitHub\hexo\blog\node_modules\hexo\lib\hexo\index.js:337:24
>     at tryCatcher (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
>     at MappingPromiseArray._promiseFulfilled (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\map.js:57:38)
>     at MappingPromiseArray.PromiseArray._iterate (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\promise_array.js:113:31)
>     at MappingPromiseArray.init (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\promise_array.js:77:10)
>     at new MappingPromiseArray (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\map.js:25:10)
>     at map (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\map.js:152:12)
>     at Function.Promise.map (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\map.js:160:12)
>     at E:\GitHub\hexo\blog\node_modules\hexo\lib\hexo\index.js:334:20
>     at tryCatcher (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
>     at Promise._settlePromiseFromHandler (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\promise.js:504:31)
>     at Promise._settlePromise (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\promise.js:561:18)
>     at Promise._settlePromise0 (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\promise.js:606:10)
>     at Promise._settlePromises (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\promise.js:685:18)
>     at Async._drainQueue (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\async.js:138:16)
>     at Async._drainQueues (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\async.js:148:10)
> FATAL spawnSync E:\Installed_Software\nodejs\node.exe ETIMEDOUT
> Error: spawnSync E:\Installed_Software\nodejs\node.exe ETIMEDOUT
>     at exports._errnoException (util.js:1008:11)
>     at Object.spawnSync (child_process.js:453:20)
>     at request (E:\GitHub\hexo\blog\node_modules\urllib-sync\index.js:33:16)
>     at Hexo.module.exports (E:\GitHub\hexo\blog\node_modules\hexo-generator-douban\lib\generator.js:16:15)
>     at Hexo.tryCatcher (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
>     at Hexo.<anonymous> (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\method.js:15:34)
>     at E:\GitHub\hexo\blog\node_modules\hexo\lib\hexo\index.js:337:24
>     at tryCatcher (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
>     at MappingPromiseArray._promiseFulfilled (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\map.js:57:38)
>     at MappingPromiseArray.PromiseArray._iterate (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\promise_array.js:113:31)
>     at MappingPromiseArray.init (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\promise_array.js:77:10)
>     at new MappingPromiseArray (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\map.js:25:10)
>     at map (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\map.js:152:12)
>     at Function.Promise.map (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\map.js:160:12)
>     at E:\GitHub\hexo\blog\node_modules\hexo\lib\hexo\index.js:334:20
>     at tryCatcher (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
>     at Promise._settlePromiseFromHandler (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\promise.js:504:31)
>     at Promise._settlePromise (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\promise.js:561:18)
>     at Promise._settlePromise0 (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\promise.js:606:10)
>     at Promise._settlePromises (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\promise.js:685:18)
>     at Async._drainQueue (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\async.js:138:16)
>    at Async._drainQueues (E:\GitHub\hexo\blog\node_modules\bluebird\js\release\async.js:148:10)

**本来一切都好好的，突然出现了上面的问题，然后google到了这里，一切配置都是正确配置的，最后瞎找了半天，看到了[这样的一个问题](https://github.com/hexojs/hexo/issues/1223)，按他说的试了一下，reinstall了hexo-generator-douban，fixed well！问题就解决了！好奇怪啊啊啊**

**Comment by Greenwicher** [comment]
@percy507 我也按照同样的方法进行了操作，但依旧会有上面的错误。

先删除豆瓣插件
`npm uninstall hexo-generator-douban`

然后重新安装豆瓣插件
`npm install hexo-generator-douban --save`

然后在_config.yml里设置豆瓣帐号和插件使用的说明，但最终依旧还是有上面的问题（大概试过很多次hexo g之后，才能成功一次）。

**Comment by percy507** [comment]
@Greenwicher 
不好意思了，我也不知道你的问题该怎么解决，毕竟我也是新手。
提个建议 **`仔细查看那些错误的信息，然后google你觉得值得google的错误信息`**

比如我上面的错误信息，我多次看到了 `\bluebird\js\release\promise.js:` 然后我添加了关键词（`hexo` `error`）google它，就找到了上面给的链接，然后就解决了问题了。

[更高效地使用搜索引擎](http://blog.percymong.com/2016/08/01/search-engines/)
